services:
  network_clickhouse:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.clickhouse
    environment:
      CLICKHOUSE_PASSWORD: $NETWORK_CLICKHOUSE_CLICKHOUSE_PASSWORD
      CLICKHOUSE_URL: $NETWORK_CLICKHOUSE_CLICKHOUSE_URL
      CLICKHOUSE_USERNAME: $NETWORK_CLICKHOUSE_CLICKHOUSE_USERNAME
      HASURA_SERVICE_TOKEN_SECRET: $NETWORK_CLICKHOUSE_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $NETWORK_CLICKHOUSE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $NETWORK_CLICKHOUSE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4842:8080
