services:
  network_kafka_sink:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.kafka_sink
    environment:
      CONNECTION_URI: $NETWORK_KAFKA_SINK_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $NETWORK_KAFKA_SINK_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $NETWORK_KAFKA_SINK_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $NETWORK_KAFKA_SINK_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4040:8080
