POST http://localhost:3280/v1/api/rest/users
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ

{
    "email": "johndoe@example.com",
    "id": 101,
    "password": "$2a$10$DSRHAPZP0fuEFioGOPOdW.kgFWZvQgmMihaBYsUs8rO4cdHFFK7Sc",
    "roles": "customer"
}