services:
  customer_stripe:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $CUSTOMER_STRIPE_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $CUSTOMER_STRIPE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CUSTOMER_STRIPE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6775:8080
