services:
  auth_search:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $AUTH_SEARCH_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $AUTH_SEARCH_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $AUTH_SEARCH_OTEL_SERVICE_NAME
      BRAVE_API_KEY: $AUTH_SEARCH_BRAVE_API_KEY
      PERPLEXITY_API_KEY: $AUTH_SEARCH_PERPLEXITY_API_KEY
      GEMINI_API_KEY: $AUTH_SEARCH_GEMINI_API_KEY
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8956:8080
