services:
  app_aml:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.aml
    environment:
      CONNECTION_URI: $APP_AML_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_AML_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_AML_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_AML_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5882:8080
