services:
  erp_operations:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.operations
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $ERP_OPERATIONS_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $ERP_OPERATIONS_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $ERP_OPERATIONS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $ERP_OPERATIONS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5274:8080
