services:
  revops_clari:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.clari
    environment:
      CONNECTION_URI: $REVOPS_CLARI_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $REVOPS_CLARI_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $REVOPS_CLARI_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $REVOPS_CLARI_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7480:8080
