services:
  customer_mongo:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.mongo
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $CUSTOMER_MONGO_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $CUSTOMER_MONGO_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $CUSTOMER_MONGO_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CUSTOMER_MONGO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5119:8080
