{
 "title": "Hasura Health",
 "description": "Hasura Health Dashboards",
 "tags": [ "hasura" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Check",
   "type": "stat",
   "description": "The HTTP health check status of Hasura services from /healthz endpoint.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (instance) (probe_success{instance=~\".*healthz$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Health Check",
   "type": "stat",
   "description": "Health check status of a particular data source, corresponding to the output of /healthz/sources. Note: you need to add health check settings to data source to enable this metric. https://hasura.io/docs/latest/deployment/health-checks/source-health-check/ ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (source_name) (hasura_source_health{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Version",
   "type": "stat",
   "description": "Current metadata resource version, if any; otherwise -1",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hasura_metadata_resource_version{job=~\"$job\"} ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Health Check Latency",
   "type": "timeseries",
   "description": "The latency of HTTP requests to the /healthz endpoint",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\".+healthz$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "description": "Postgres connection usage from GraphQL Engine instances",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (role,conn_info,source_name) (hasura_postgres_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}