{
 "title": "Hasura Overview",
 "description": "The overview dashboard for Hasura GraphQL Engine",
 "tags": [ "hasura" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GraphQL Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Query",
   "type": "stat",
   "description": "Number of GraphQL Query requests",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Mutation",
   "type": "stat",
   "description": "Number of GraphQL Mutation requests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"mutation\",instance=~\"$instance\",job=~\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_http_connections{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Websocket Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_websocket_connections{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "description": "Current number of active subscriptions",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"})"
    }
   ]
  },
  {
   "title": "Subscription Latency (P95)",
   "type": "stat",
   "description": "P95 latency of active subscriptions",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Active Streaming Requests",
   "type": "stat",
   "description": "Current number of active streaming requests",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\"})"
    }
   ]
  },
  {
   "title": "Streaming Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Streaming requests",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Active Subscription Workers",
   "type": "stat",
   "description": "Current active number of subscription pollers running",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hasura_active_subscription_pollers{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"})"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "stat",
   "description": "Number of cache requests per minute",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_cache_request_count{job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  { "title": "Event Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Event Trigger",
   "type": "stat",
   "description": "Number of event trigger invocations",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_event_invocations_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Event Trigger Latency (P95)",
   "type": "stat",
   "description": "P95 latency of the time taken for an event to be delivered since it's been created (if first attempt) or retried (after first attempt).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Failed Event Trigger",
   "type": "stat",
   "description": "Number of failed event trigger invocations per minute",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_event_invocations_total{job=~\"$job\",instance=~\"$instance\",status=\"failed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Event Queue Time Latency (P95)",
   "type": "stat",
   "description": "P95 latency of the queue time for an event already in the processing queue",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_queue_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Cron Trigger",
   "type": "stat",
   "description": "Number of cron trigger invocations",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_cron_events_invocation_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Cron Trigger",
   "type": "stat",
   "description": "Number of failed cron trigger invocations",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_cron_events_invocation_total{job=~\"$job\",instance=~\"$instance\",status=\"failed\"}[$__range]))"
    }
   ]
  },
  { "title": "GraphQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Query Request Rate",
   "type": "timeseries",
   "description": "The rate of GraphQL Query requests processed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Mutation Request Rate",
   "type": "timeseries",
   "description": "The rate of GraphQL Mutation processed requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(increase(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "timeseries",
   "description": "Current number of active subscriptions",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"})",
     "legendFormat": "Subscriptions"
    }
   ]
  },
  {
   "title": "Subscription Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of active subscriptions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"live-query\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Streamings",
   "type": "timeseries",
   "description": "Current number of active streaming requests",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(hasura_active_subscriptions{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\"})",
     "legendFormat": "Streamings"
    }
   ]
  },
  {
   "title": "Streaming Latency (P95)",
   "type": "timeseries",
   "description": "P95 streaming latency of Hasura instances",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_subscription_total_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",subscription_kind=\"streaming\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Event & Cron Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Event Processing Rate",
   "type": "timeseries",
   "description": "Processed event triggers rate per interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_event_invocations_total{job=~\"$job\",instance=~\"$instance\",status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(hasura_event_invocations_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Event Processing Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of processed event triggers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_processing_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cron Processing Rate",
   "type": "timeseries",
   "description": "The rate of cron events processed",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cron_events_invocation_total{job=~\"$job\",instance=~\"$instance\",status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(hasura_cron_events_invocation_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Event Queue Time (P95)",
   "type": "timeseries",
   "description": "P95 latency of the queue time for an event already in the processing queue",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_event_queue_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (job,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "description": "Current number of active HTTP connections (excluding WebSocket connections)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (hasura_http_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "WebSocket Connections",
   "type": "timeseries",
   "description": "Current number of active WebSocket connections",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job) (hasura_websocket_connections{job=~\"$job\",instance=~\"$instance\"}) ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "description": "Postgres connection usage from GraphQL Engine instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (role,conn_info,source_name) (hasura_postgres_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Request Rate",
   "type": "timeseries",
   "description": "Total number of incoming requests for cache lookup",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\",instance=~\"$instance\",status=\"hit\"}[$__rate_interval]))",
     "legendFormat": "Cache Hit"
    },
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Postgres Connection Init Time (P95)",
   "type": "timeseries",
   "description": "P95 Latency taken to establish and initialise a new PostgreSQL connection",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_postgres_connection_init_time_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (role,conn_info,source_name,le))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Postgres Pool Wait Time (P95)",
   "type": "timeseries",
   "description": "P95 Latency taken to acquire a connection from the pool",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_postgres_pool_wait_time_bucket{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) by (role,conn_info,source_name,le))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}