{
 "title": "Hasura HTTP GraphQL",
 "description": "Hasura dashboards for HTTP GraphQL requests",
 "tags": [ "hasura" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(hasura_http_connections,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(hasura_http_connections{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Lineage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(api) (count_over_time({container=\"emergent_hasura\"} |= `query` | json | regexp `\"query\":\"[^\"]*(?P<operation_type>query|mutation|subscription)\\s+(?P<api>\\w+)[^\\\"]*\"` | line_format `{{.operation_type}}_{{.api}}` | operation_type != `` [$__range]))"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "description": "Number of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",instance=~\"$instance\",job=~\"$job\",response_status=\"success\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Total Mutations",
   "type": "stat",
   "description": "Number of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"mutation\",job=~\"$job\",instance=~\"$instance\", response_status=\"success\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "SUM(increase(hasura_graphql_requests_total{operation_type=\"query\",job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "stat",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__range])) by (le))"
    }
   ]
  },
  { "title": "GraphQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Query Request Rate",
   "type": "timeseries",
   "description": "The request rate of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation Request Rate",
   "type": "timeseries",
   "description": "The request rate of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "timeseries",
   "description": "The error rate of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation Error Rate",
   "type": "timeseries",
   "description": "The Error rate of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(hasura_graphql_requests_total{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\",response_status=\"failed\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Query requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"query\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mutation Latency (P95)",
   "type": "timeseries",
   "description": "P95 latency of GraphQL Mutation requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(hasura_graphql_execution_time_seconds_bucket{job=~\"$job\",instance=~\"$instance\",operation_type=\"mutation\"}[$__rate_interval])) by (job,instance,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "HTTP Connections",
   "type": "timeseries",
   "description": "Current number of active HTTP connections (excluding WebSocket connections)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (hasura_http_connections{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Request Rate",
   "type": "timeseries",
   "description": "Total number of incoming requests for cache lookup",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\",status=\"hit\"}[$__rate_interval]))",
     "legendFormat": "Cache Hit"
    },
    {
     "expr": "sum(rate(hasura_cache_request_count{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer of HTTP Requests ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_http_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + increase(hasura_http_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Action Data Transfer",
   "type": "timeseries",
   "description": "Data Transfer of external action webhook requests ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (increase(hasura_action_request_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]) + increase(hasura_action_response_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}