name: ${CONTAINER_PREFIX}
services:
  # Databases
  postgres:
    image: postgres
    container_name: ${CONTAINER_PREFIX}_postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  mongodb:
    image: mongo
    container_name: ${CONTAINER_PREFIX}_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - mongodb-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=aml
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    extra_hosts:
      - local.hasura.dev=host-gateway
  mongo-seed:
    env_file:
        - .env
    build:
        context: ./mongo_seed
        dockerfile: Dockerfile
        args:
            - DATABASE_URI=mongodb://local.hasura.dev:27017/aml
            - USERNAME=presales
            - PASSWORD=${MONGO_PASSWORD}
    depends_on:
        - mongodb
    extra_hosts:
      - local.hasura.dev=host-gateway

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  caching:
    build:
      context: https://github.com/hasura/engine-plugin-caching.git#f59acfe4004c869181de83be78d0f5d48459ef3c
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      CACHING_PLUGIN_SECRET: ${CACHING_PLUGIN_SECRET}
      CACHING_PLUGIN_REDIS_URL: ${CACHING_PLUGIN_REDIS_URL}
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ../plugins/caching-config.js:/app/src/config.js

  restified:
    container_name: ${CONTAINER_PREFIX}_restified
    build:
      context: https://github.com/hasura/engine-plugin-restified-endpoint.git#paritosh/express-server
      target: base
    restart: unless-stopped
    ports:
      - "8788:8788"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${RESTIFIED_EXPORTER_OTLP_ENDPOINT}
      GRAPHQL_SERVER_URL: ${RESTIFIED_GRAPHQL_SERVER_URL}
      RESTIFIED_PLUGIN_SECRET: ${RESTIFIED_PLUGIN_SECRET}
      PORT: 8788
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ../plugins/restified/aml-config.ts:/app/src/config.ts
    command: ["bash", "-c", "npm run build && npm run serve"]

volumes:
  postgres-data:
  mongodb-data:
