services:
  app_ecommerce_mongodb:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.ecommerce_mongodb
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_ECOMMERCE_MONGODB_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_ECOMMERCE_MONGODB_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_ECOMMERCE_MONGODB_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_ECOMMERCE_MONGODB_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8788:8080
