services:
  patient_ops_operations:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.operations
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $PATIENT_OPS_OPERATIONS_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $PATIENT_OPS_OPERATIONS_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $PATIENT_OPS_OPERATIONS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PATIENT_OPS_OPERATIONS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6516:8080
