services:
  patient_ops_operations:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.operations
    environment:
      CONNECTION_URI: $PATIENT_OPS_OPERATIONS_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $PATIENT_OPS_OPERATIONS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $PATIENT_OPS_OPERATIONS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PATIENT_OPS_OPERATIONS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5622:8080
