services:
  support_atlas:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.atlas
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $SUPPORT_ATLAS_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $SUPPORT_ATLAS_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $SUPPORT_ATLAS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $SUPPORT_ATLAS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8795:8080
