services:
  patient_ops_patients:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.patients
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $PATIENT_OPS_PATIENTS_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $PATIENT_OPS_PATIENTS_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $PATIENT_OPS_PATIENTS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PATIENT_OPS_PATIENTS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4799:8080
