services:
  network_clickhouse:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.clickhouse
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $NETWORK_CLICKHOUSE_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $NETWORK_CLICKHOUSE_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $NETWORK_CLICKHOUSE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $NETWORK_CLICKHOUSE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4045:8080
