services:
  auth_auth:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.auth
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $AUTH_AUTH_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $AUTH_AUTH_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $AUTH_AUTH_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $AUTH_AUTH_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4444:8080
