GET http://localhost:3280/v1/api/rest/users?limit=5&offset=3
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ

###
GET http://localhost:3280/v1/api/rest/user/7
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ

###
POST http://localhost:3280/v1/api/rest/users
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ

{
    "email": "johndoe@example.com",
    "id": 101,
    "password": "$2a$10$DSRHAPZP0fuEFioGOPOdW.kgFWZvQgmMihaBYsUs8rO4cdHFFK7Sc",
    "roles": "customer"
}

###
PUT http://localhost:3280/v1/api/rest/users/101/password
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ

{
    "password": "newpassword"
}

###
DELETE http://localhost:3280/v1/api/rest/users/101
Content-Type: application/json
hasura-m-auth: zZkhKqFjqXR4g5MZCsJUZCcoPyZ
