services:
  app_aml_monitoring:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.aml_monitoring
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_AML_MONITORING_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $APP_AML_MONITORING_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_AML_MONITORING_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_AML_MONITORING_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4441:8080
