services:
  app_postgres_retail:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.postgres_retail
    environment:
      FULLY_QUALIFY_TABLE_NAMES: $APP_POSTGRES_RETAIL_FULLY_QUALIFY_TABLE_NAMES
      HASURA_LOG_LEVEL: $APP_POSTGRES_RETAIL_HASURA_LOG_LEVEL
      HASURA_SERVICE_TOKEN_SECRET: $APP_POSTGRES_RETAIL_HASURA_SERVICE_TOKEN_SECRET
      JDBC_SCHEMAS: $APP_POSTGRES_RETAIL_JDBC_SCHEMAS
      JDBC_URL: $APP_POSTGRES_RETAIL_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_POSTGRES_RETAIL_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_POSTGRES_RETAIL_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7358:8080
