name: axiomtelco
services:
  # Databases
  postgres:
    image: postgres
    container_name: axiomtelco_postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  pgvector:
    image: ankane/pgvector:latest
    container_name: axiomtelco_pgvector
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./pgvector/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -q -h pgvector"
      interval: 10s
      timeout: 5s
      retries: 30

  mongodb:
    image: mongo
    container_name: axiomtelco_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - mongodb-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=holotel
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 30

  mongo-seed:
    env_file:
        - .env
    container_name: axiomtelco_mongo_seed
    build:
        context: ./mongo_seed
        dockerfile: Dockerfile
        args:
            - DATABASE_URI=mongodb://local.hasura.dev:27017/holotel
            - USERNAME=presales
            - PASSWORD=${MONGO_PASSWORD}
    depends_on:
        - mongodb
    extra_hosts:
      - local.hasura.dev=host-gateway

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: axiomtelco_clickhouse
    restart: unless-stopped
    user: "101:101"
    ports:
      - "8123:8123"
      - "9000:9000"
    hostname: clickhouse
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse/csv:/etc/clickhouse-server/csv
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/scripts/:/docker-entrypoint-initdb.d/

volumes:
  postgres-data:
  pgvector-data:
  clickhouse_data:
  mongodb-data: