{
 "title": "System Monitoring",
 "tags": [ "alerts" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Load Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg by (instance) (up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The average CPU cores usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (100 * ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) / (node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}) ))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Process CPU Seconds",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage (Process)",
   "type": "timeseries",
   "description": "Virtual memory usage per container process ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Measure the memory usage of the server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total memory" },
    { "expr": "node_memory_Active_bytes", "legendFormat": "Memory usage" }
   ]
  },
  {
   "title": "Memory usage (RAM + Swap)",
   "type": "timeseries",
   "description": "Measure the memory usage including Swap of the server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes + node_memory_SwapTotal_bytes",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_Active_bytes + (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) ",
     "legendFormat": "Memory usage"
    }
   ]
  }
 ]
}