---
- name: Apply Host Defaults
  import_playbook: playbooks/defaults.yml

- name: Manage SSH Keys
  import_playbook: playbooks/manage_ssh_keys.yml

- name: Deploy Axiom with Dependencies
  import_playbook: playbooks/axiom.yml

- name: Set up cron tasks
  import_playbook: playbooks/cron.yml
