services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    shm_size: 128mb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - ./vol/db:/data/db
