services:
  patient_ops_ops_mgmt:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $PATIENT_OPS_OPS_MGMT_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $PATIENT_OPS_OPS_MGMT_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PATIENT_OPS_OPS_MGMT_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5592:8080
