services:
  reference_reference:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.reference
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $REFERENCE_REFERENCE_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $REFERENCE_REFERENCE_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $REFERENCE_REFERENCE_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $REFERENCE_REFERENCE_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8506:8080
