name: ${CONTAINER_PREFIX}
services:
  # Databases
  postgres:
    image: postgres
    container_name: ${CONTAINER_PREFIX}_postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../build/postgres/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  pgvector:
    image: ankane/pgvector:latest
    container_name: ${CONTAINER_PREFIX}_pgvector
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ../common/pgvector/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  mongodb:
    image: mongo
    container_name: ${CONTAINER_PREFIX}_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - mongodb-data:/data/db
      - ../build/mongodb:/docker-entrypoint-initdb.d/
    environment:
      - MONGO_INITDB_DATABASE=holotel
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379

  caching:
    build:
      context: https://github.com/hasura/engine-plugin-caching.git
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      CACHING_PLUGIN_SECRET: ${CACHING_PLUGIN_SECRET}
      CACHING_PLUGIN_REDIS_URL: ${CACHING_PLUGIN_REDIS_URL}
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ../plugins/caching-config.js:/app/src/config.js

volumes:
  postgres-data:
  pgvector-data:
  mongodb-data:
