kind: Connector
version: v2
definition:
  name: inventory
  resources:
    memory: 4Gi
    cpu: "1"
  subgraph: retail_ops
  source: hasura/postgres-promptql:v1.2.12
  context: .
  envMapping:
    HASURA_CONNECTOR_PORT:
      fromEnv: RETAIL_OPS_INVENTORY_HASURA_CONNECTOR_PORT
    HASURA_SERVICE_TOKEN_SECRET:
      fromEnv: RETAIL_OPS_INVENTORY_HASURA_SERVICE_TOKEN_SECRET
    JDBC_URL:
      fromEnv: RETAIL_OPS_INVENTORY_JDBC_URL
    OTEL_EXPORTER_OTLP_ENDPOINT:
      fromEnv: RETAIL_OPS_INVENTORY_OTEL_EXPORTER_OTLP_ENDPOINT
    OTEL_SERVICE_NAME:
      fromEnv: RETAIL_OPS_INVENTORY_OTEL_SERVICE_NAME
    JAVA_OPTS: 
      fromEnv: JAVA_OPTS
