services:
  db:
    image: postgres:latest
    container_name: postgres
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      PGPORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scms
    volumes:
      - ./vol/db:/var/lib/postgresql/data
