services:
  mongodb:
    image: mongo:latest
    container_name: axiom_sco_mongodb
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ecommerce
    volumes:
      - mongodb-data:/data/db
  postgres:
    image: postgres:latest
    container_name: axiom_sco_postgres
    shm_size: 128mb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      PGPORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scms
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/entrypoint/:/docker-entrypoint-initdb.d/
volumes:
  mongodb-data:
  postgres-data:
