services:
  operations_auth:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.auth
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $OPERATIONS_AUTH_HASURA_SERVICE_TOKEN_SECRET
      JDBC_URL: $OPERATIONS_AUTH_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $OPERATIONS_AUTH_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $OPERATIONS_AUTH_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4389:8080
