query ErrorQuery {
  billing {
    customer {
      billings {
        billingDate
        customerId
        paymentStatus
        totalAmount
      }
      creditCards {
        customerId
      }
      customerPlans {
        plan {
          type
        }
      }
      customerNetworks {
        customerId
      }
      customerLinks {
        customerGuid
        NetworkPerformance {
          downloadSpeed
        }
        DataUsage {
          dataUsage
        }
        CDR {
          callType
          formatTimestamp
          timestamp
        }
        supportDB {
          memberId
          notes
          preferences {
            communication {
              emailUpdates
              smsNotifications
              appNotifications {
                enabled
              }
            }
          }
        }
      }
    }
    billingDate
  }
}
