query JoinQuery($limit: Int = 10) {
  # Get customer information with credit cards
  customers(limit: $limit) {
    firstName
    lastName
    address
    city
    state
    postcode
    segment
    creditCards {
      maskCreditCard
      expiry
    }
  }
}
