include:
  - path: globals/connector/global_functions/compose.yaml
  - path: industry/cpg/retail_ops/connector/sales/compose.yaml
  - path: industry/cpg/retail_ops/connector/inventory/compose.yaml
  - path: industry/cpg/retail_actions/connector/retail_execution/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile_inline: |-
        FROM ghcr.io/hasura/v3-engine
        COPY ./build /md/
    develop:
      watch:
        - action: sync+restart
          path: engine/build
          target: /md/
    env_file:
      - engine/.env.engine
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "3280"
        target: 3000
  otel-collector:
    command:
      - --config=/etc/otel-collector-config.yaml
    environment:
      HASURA_DDN_PAT: ${HASURA_DDN_PAT}
    image: otel/opentelemetry-collector:0.104.0
    ports:
      - mode: ingress
        protocol: tcp
        published: "4317"
        target: 4317
      - mode: ingress
        protocol: tcp
        published: "4318"
        target: 4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  promptql-playground:
    environment:
      CORS_ORIGINS: ${CORS_ORIGINS:-https://console.hasura.io,https://promptql.console.hasura.io}
      ENGINE_URL: ${HASURA_DDN_URL:-http://engine:3000/v1/sql}
      HASURA_LLM_URI: ${HASURA_LLM_URI:-https://llm.promptql.pro.hasura.io}
      LLM: ${LLM:-hasura}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://host.docker.internal:4317}
      PROMPTQL_SECRET_KEY: ${PROMPTQL_SECRET_KEY}
      PROMPTQL_URI: ${PROMPTQL_URI:-wss://runtime.promptql.pro.hasura.io}
    image: us-east4-docker.pkg.dev/promptql-execution-service/promptql-public/promptql-playground-local
    labels:
      io.hasura.ddn.service-name: promptql-playground
    ports:
      - 3282:5000
