include:
  - path: industry/telco/customer/connector/aurora/compose.yaml
  - path: industry/telco/customer/connector/mongo/compose.yaml
  - path: industry/telco/customer/connector/logic/compose.yaml
  - path: industry/telco/support/connector/atlas/compose.yaml
  - path: industry/telco/support/connector/vector/compose.yaml
  - path: industry/telco/network/connector/clickhouse/compose.yaml
  - path: industry/telco/auth/connector/auth/compose.yaml
  - path: industry/telco/network/connector/kafka_sink/compose.yaml
  - path: globals/connector/global_functions/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile: Dockerfile.engine
      pull: true
    environment:
      AUTHN_CONFIG_PATH: /md/auth_config.json
      ENABLE_CORS: "true"
      ENABLE_SQL_INTERFACE: "true"
      INTROSPECTION_METADATA_FILE: /md/metadata.json
      METADATA_PATH: /md/open_dd.json
      OTLP_ENDPOINT: http://local.hasura.dev:4317
    extra_hosts:
      - local.hasura.dev:host-gateway
    labels:
      io.hasura.ddn.service-name: engine
    ports:
      - 3280:3000
  otel-collector:
    command:
      - --config=/etc/otel-collector-config.yaml
    environment:
      HASURA_DDN_PAT: ${HASURA_DDN_PAT}
    image: otel/opentelemetry-collector:0.104.0
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml