services:
  customer_logic:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $CUSTOMER_LOGIC_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $CUSTOMER_LOGIC_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $CUSTOMER_LOGIC_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5627:8080
