name: gtm
services:
  # Databases
  postgres:
    image: postgres
    container_name: gtm_postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  pgvector:
    image: ankane/pgvector:latest
    container_name: gtm_pgvector
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data
      - ./pgvector/:/docker-entrypoint-initdb.d/
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - 6379:6379

  caching:
    build:
      context: https://github.com/hasura/engine-plugin-caching.git#64b184d2ea530e6314900c5177e822d2384b8fd3
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      CACHING_PLUGIN_SECRET: ${CACHING_PLUGIN_SECRET}
      CACHING_PLUGIN_REDIS_URL: ${CACHING_PLUGIN_REDIS_URL}
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ../plugins/caching/gtm-config.js:/app/src/config.js

  restified:
    container_name: ${CONTAINER_PREFIX}_restified
    build:
      context: https://github.com/hasura/engine-plugin-restified-endpoint.git#paritosh/express-server
      target: base
    restart: unless-stopped
    ports:
      - "8788:8788"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: ${RESTIFIED_EXPORTER_OTLP_ENDPOINT}
      GRAPHQL_SERVER_URL: ${RESTIFIED_GRAPHQL_SERVER_URL}
      RESTIFIED_PLUGIN_SECRET: ${RESTIFIED_PLUGIN_SECRET}
      PORT: 8788
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ../plugins/restified/gtm-config.ts:/app/src/config.ts
    command: ["bash", "-c", "npm run build && npm run serve"]


  rate-limit:
    container_name: ${CONTAINER_PREFIX}_ratelimit
    build:
      context: https://github.com/hasura/engine-plugin-rate-limit.git
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DEBUG: ratelimit*
      OTEL_EXPORTER_OTLP_ENDPOINT: ${RATELIMIT_EXPORTER_OTLP_ENDPOINT}
      HASURA_DDN_PLUGIN_CONFIG_PATH: /app/src/ratelimit
    extra_hosts:
      - local.hasura.dev=host-gateway
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://local.hasura.dev:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
        - ../plugins/ratelimit:/app/src/ratelimit

volumes:
  postgres-data:
  pgvector-data:
