services:
  support_atlas:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-mongodb:v1.0.0
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $SUPPORT_ATLAS_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $SUPPORT_ATLAS_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $SUPPORT_ATLAS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $SUPPORT_ATLAS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "7553"
        protocol: tcp
