services:
  app_scms_postgres:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.scms_postgres
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_SCMS_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      JDBC_SCHEMAS: $APP_SCMS_POSTGRES_JDBC_SCHEMAS
      JDBC_URL: $APP_SCMS_POSTGRES_JDBC_URL
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_SCMS_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_SCMS_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5238:8080
