- name: Install prerequisites for Axiom
  import_playbook: ddn.yml

- name: Configure Docker for Axiom
  import_playbook: configure_docker.yml

- name: Clone and configure Axiom repository
  hosts: demo_servers
  become: true
  tasks:
    - name: Clone axiom repository
      ansible.builtin.git:
        repo: https://github.com/hasura/axiom.git
        dest: /home/ubuntu/axiom
        version: main
        accept_hostkey: true
      become: true
      become_user: ubuntu

    - name: Load environment variables from .env
      ansible.builtin.include_vars:
        file: ../.env
        name: env_vars

    - name: Setup environment variables from Ansible -> Docker
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/env_vars.j2"
        dest: "{{ env_file_path }}"
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      vars:
        env_file_path: "/home/ubuntu/axiom/.data/{{ demo_profile }}/.env"

    - name: Turn on the demo
      ansible.builtin.command: /usr/local/bin/ddn run docker-start-{{ demo_profile }}
      args:
        chdir: /home/ubuntu/axiom/hasura
      register: ddn_demo_start
      changed_when: false
      become: true
      become_user: ubuntu
