---
- name: Install prerequisites for Axiom
  import_playbook: ddn.yml

- name: Configure Docker for Axiom
  import_playbook: configure_docker.yml

- name: Clone and configure Axiom repository
  hosts: demo_servers
  become: true
  tasks:
    - name: Ensure git is installed
      ansible.builtin.apt:
        name: git
        state: present

    - name: Ensure git-lfs is installed
      ansible.builtin.apt:
        name: git-lfs
        state: present

    - name: Ensure /home/ubuntu/axiom-demo/<profile> exists
      ansible.builtin.file:
        path: /home/ubuntu/axiom-data/{{ demo_profile }}
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        state: directory
        recurse: true

    - name: Upload demo profile from .data directory
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../../../.data/{{ demo_profile }}/"
        dest: "/home/ubuntu/axiom-data/{{ demo_profile }}/"
        recursive: true
        delete: true
        rsync_opts:
          - "--exclude=.*"
      delegate_to: localhost
      become: false

    - name: Ensure /home/ubuntu/axiom-demo/plugins exists
      ansible.builtin.file:
        path: /home/ubuntu/axiom-data/plugins
        owner: ubuntu
        group: ubuntu
        mode: "0755"
        state: directory
        recurse: true

    - name: Upload demo profile from .data directory
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../../../.data/plugins/"
        dest: "/home/ubuntu/axiom-data/plugins/"
        recursive: true
        delete: true
        rsync_opts:
          - "--exclude=.*"
      delegate_to: localhost
      become: false

    - name: Load environment variables from .env
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../.env"
        name: env_vars

    - name: Override RESTIFIED_GRAPHQL_SERVER_URL based on server
      ansible.builtin.set_fact:
        restified_graphql_server_url: "{{ hostvars[inventory_hostname]['graphql_url'] | default(' http://local.hasura.dev:3280/graphql') }}"

    - name: Setup environment variables from Ansible -> Docker
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/env_vars.j2"
        dest: "{{ env_file_path }}"
        owner: ubuntu
        group: ubuntu
        mode: "0600"
      vars:
        env_file_path: "/home/ubuntu/axiom-data/{{ demo_profile }}/.env"

    - name: Turn on the demo
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/axiom-data/{{ demo_profile }}
        files:
          - compose.yaml
        build: always
        pull: always
        state: present
        remove_orphans: true
      become: true
