---
- name: Set up Docker
  hosts: hosts
  become: true
  tasks:
    - name: Check if Docker is already installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: true
      changed_when: false

    - name: Install ca-certificates and curl
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: docker_check.rc != 0

    - name: Create Docker keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
      when: docker_check.rc != 0

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: false
      when: docker_check.rc != 0

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      notify: Refresh APT cache
      when: docker_check.rc != 0

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      when: docker_check.rc != 0

    - name: Create Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

  handlers:
    - name: Refresh APT cache
      ansible.builtin.apt:
        update_cache: true
