---
- name: Ensure SSH keys are present
  hosts: hosts
  become: true
  tasks:
    - name: Add SSH keys to authorized_keys
      ansible.posix.authorized_key:
        user: "ubuntu"
        key: "{{ item.key }}"
        state: present
      loop:
        - name: adam.malone@hades
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCeMGVosn2JB/RBWXQ+zVngRCHp9vGcoPiL9yh8xFd9mR\
                Twt7Q5BWSneANU7odpYTHQZRWETxvqzuxCwqMLGgOLzi7xBBfguMj3oRzrYKXTOPRyfF/fjtzr0LEYdHL6R\
                iYEfRmIW70fm5jAGj32DBcIiEMF69dv9AeOuXic4HaEAQxHahuvA1m4DYhCycBGay3wOjMAMFeVN2yQqYSv\
                LKsp4kASHunssLsiEiHzUhClqlUQ3E8oEWc3BbJenkmjSDtOLKgOQs23ZZR7x1EnVtCX0rzRIHGkmPvi7W8\
                RIDD9qWfa3RKf9jxnw53MGH4p4R3PkZPFgv9d9igUG2ntQkoD2bxRzzJtWVlCnFWtu2MaU3KcKXLV6mvxDb\
                H2oPGEn1Qyr/z+cIcoLZ5bkZw1bIKNOxb0fuazLUlMgdzck39YJJkOG+SJPc1FZLT4Ew+R48oDe63gDI4vM\
                p2uuvN4auiMhTX0Xzk/Xnu5tbH8rQyfFKWNxDkti1O87IhoAsjKvvxijkQWDO4zbNMtSjenQMpcPmi09ZSE\
                u00nW7um6rCZNXiKztje0Ln7L2fe2EgAnM6CAd6Bd8DowypdHGF0F7dpzF2PPaRDQl+EXwUKI+NfPCgrKlR\
                XgiH23RThYi0/Nz87w6Q2lm5Avv4xWP3zLdHjg/3FrAjHB+UuXDhe0Fryw== adam.malone@hades"
        - name: rajusunny@hasura.io
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEvHPxvOCnUhFr88x1xbmV8sE/Zt4qCoCNS92iQEnubnI\
                xOKlqHpnUxVq/s/vQaJvjSb0uywCDckol+eI7r6rMAM0qhZ4OooNgN8SZFzMr8Z4yJNEusU2d8I2LaVoW+0\
                Wx6v0ff7Dk5oE4Ar5sHS5SVz2lHsj/KWIEyK+W0LyHm8bX3D+MVFAnY/6SEpY8UwWhHZHyWT/RjPY24FFvC\
                ivmeUJCK0huRFSkeh2dJQSc9SkSEXA3uVstlJbHghIlsbdlAtYpgYVCipVoePTcODsFyvdGzBhieZLB/TRI\
                ILghIkUrDMhRiT8bmT3oymGU8wuET6cGHDLpdtzlkxmuE4r0H18xcdIuxCCUh6SWhTlFGVGI0gLZ0W9rWaq\
                QZMILIQ/qaWAhItzmx1PZzF32ucWpqhq0x54EJwugXPGuiu7Aai970ZRyYz5sFmspC7XKM2sg6oBsd3k6+r\
                DD1QR7h9IAb2SuP3RDsvlF+7wehqydI5eKiJI8qkQ65l4+X16iJpM= rajusunny@hasura.io"
        - name: eric.nelson@hasura.io
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+2E26FT/4bw8jyYYHi6igwYF+icRiwlW/d2Tyr2kkCen\
                h6OcY4lJYQWkNh24cmEts6xWEhOjvtTaI9rR2oj9LA90bd3B9dr/TOEgj1lUdVonIhZCZdzrOQ7DnklEDuK\
                1g82E6tkXPJcdMyav8usWsEXZTJBJwjx4cKxSpv6edrYkBzoYaHtfywtm6KD/QaWQMOIz+0F0q6Xsvy4r4S\
                o7B6WmblXIJS8rcLz/eZiBE7W6TdwfaFQTilXfp6I6bGk5XEmYCVCOQU2M3yIfGmRRV230i72xbnWXLZCtH\
                B84zElJgxMjq0m8TdexUV2cTjx8GLeCUg1PZzcGsgeo5mMhRaJCSZr3ec3yjh3OYu5+bNoxiwvl0nxzRDGD\
                nx5Kc4yklVBjaBr36w8nsl3feeIQmO0NiZDs5Fk/BJBkuEf1QCsxLnvwmjumiDATL8hbKBAy/osFvgfBcRm\
                VUnSTfiCIPJMbAURDJIIPXeSBJOQqCZ+RpYakwI/f4c6TmH4hnqRs= eric@mjolnir.245.im"
        - name: sandip@hasura.io
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwf/v1DCiGFwPboRHQjf/DD5Vgt00t2xu/QQfqbMXhBSn\
                O0eePawddI6NyYsu6AvwdkcTuoM74mT7wmp7eJfaS3OTlBannlxqag7FEdrnP/QQEXIgGTEVNSBrKkBuTVB\
                rnmBhmRDpZBROAPLka2IIUHsjtVzncJ1Ovjtneud1CQ/ZqGgR+FaPYDSM2mghoMCJWAjQivwImPK+HEiF20\
                lVDpFlLqY47nAnZBL1jxlOKipOWdyKot47joxpT+rHh46oqq8Isrepn3REb3K95oI6UvND3e4l4oOhbcvrn\
                r+wo0MKGk5DzAOCOp0tC1j3qaqUHQ0AjWSqYG1uEDoAsBBJK7MYsUwzUocWoJf2pRwaX150XMq3I+sLA2fn\
                H7WekOnO4LgtABtS0ckTKCLSXJDAOyQxoDe1zV3iQhYHzkLNp0h810KMWmVu8RfDFqQNPMS0NMbu55rGyn4\
                9ByIMtSxYUylOyS6Ar4JVFVguPZFItmPWOvKdBY9xM0xGopoPMbHU= sandipd@Sandips-MacBook-Pro.local"
        - name: brian.walter@hasura.io
          key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9Z8VsB8FKJMahiRBT2iMy7lfra/1pJb4R/I1EUCNsK"
        - name: srini.sankar@hasura.io
          key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJGAzwfFSRua8vQE3EHAT6Gz9PrS8YgVHGbf+gF3J81U"
        - name: gourav@hasura.io
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfQY73wM5mPRDXGPTyV4lfJwPJBINxcVNKPXed47gR4nHB+mh4l/vmzQNpLri8jt8b7cFlC8+q+02k1SikV2Ob3deGdC7pc34Liv1BTbmcl6P5hi6PfKe87i7AXqkMq5X+JFJcI4FAuyVlgmvywHM29r/kAoK/2gb85vkUxk0G67rX3k+Xy01q0fPzecleLNlWRrwkPsSHhUHIRIr2fqSJP4UFRqYlCjxBx6Ic+vcN2RJf/I32AxD4mNPe+Q3dHYPe/Ue2xR3hLkwlzQG1YUAXCIcS1JVebC9dsch9Rr5/BR3pYleaqXf3IEhLzjFKwAZCfcInFof7n+TKqQQkDYw86Uh5Pl1gOOpdqaepUzNsU5tB7Lm2ADO/90n8X73ChhwbT/0BkwZKhs/iYOKCA4p1sBGHxiKfvYAV8o/KVu1FsUykkhF19TVP9za1MtJOOSlKNCA8uvFOu4ItdYHi0YMEAGU4ZQsdPTMySEDODWLlWaXMO/TYoCA1/Euyg1kr2StPNSK+Kj+fN/DenD4uKnoopCk8sJaOJlGg6RPTLvRSsx/zilK2mlPXn5TwVX+Z7JOLhttNQpA3ynMmhgVSIpiSRafGukq66+SwkL10FQ2Ke3tTkXQU12A5Lu84cRz3HJlMQAIDLVONXZLCKY+kiMgoPTkPIN8INkzQtUtqLDusNQ== gouravhasura@gourav-MacBook-Pro"
