---
# Basic Nginx Playbook
#
# This playbook sets up nginx by:
# 1. Installing nginx
# 2. Configuring nginx to listen on port 80
# 3. Proxying requests to a configurable backend port
# 4. Restricting access to localhost and Cloudflare IPs only
#
# Required Variables (set in inventory):
# - server_name: The domain name to respond to
# - backend_port: The local port to proxy to (default: 8080)

- name: Setup Nginx
  hosts: nginx_servers
  become: true
  vars:
    nginx_backend_port: "{{ backend_port | default('8080') }}"

    # Cloudflare IPv4 ranges
    cloudflare_ipv4_ranges:
      - "173.245.48.0/20"
      - "103.21.244.0/22"
      - "103.22.200.0/22"
      - "103.31.4.0/22"
      - "141.101.64.0/18"
      - "108.162.192.0/18"
      - "190.93.240.0/20"
      - "188.114.96.0/20"
      - "197.234.240.0/22"
      - "198.41.128.0/17"
      - "162.158.0.0/15"
      - "104.16.0.0/13"
      - "104.24.0.0/14"
      - "172.64.0.0/13"
      - "131.0.72.0/22"

    # Cloudflare IPv6 ranges
    cloudflare_ipv6_ranges:
      - "2400:cb00::/32"
      - "2606:4700::/32"
      - "2803:f800::/32"
      - "2405:b500::/32"
      - "2405:8100::/32"
      - "2a06:98c0::/29"
      - "2c0f:f248::/32"

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Remove default nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create nginx configuration
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: "/etc/nginx/sites-available/{{ server_name }}"
        owner: root
        group: root
        mode: "0644"
      notify: Reload nginx

    - name: Enable site
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ server_name }}"
        dest: "/etc/nginx/sites-enabled/{{ server_name }}"
        state: link
      notify: Reload nginx

    - name: Test nginx configuration
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Start and enable nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
