services:
  patient_ops_patients:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.patients
    environment:
      CONNECTION_URI: $PATIENT_OPS_PATIENTS_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $PATIENT_OPS_PATIENTS_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $PATIENT_OPS_PATIENTS_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $PATIENT_OPS_PATIENTS_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6650:8080
