name: Axiom Ansible Lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ${{ github.workspace }}/infra/ansible
          requirements_file: ${{ github.workspace }}/infra/ansible/requirements.yml
