name: Axiom Ansible Lint
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core>=2.20.0 ansible-lint
      - name: Run ansible-lint
        run: |
          cd ${{ github.workspace }}/infra/ansible
          ansible-galaxy install -r requirements.yml
          ansible-lint
