name: Axiom auto-test + auto-deploy

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for [no-op] in commit message
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^\[no-op\] ]]; then
            echo "no_op=true" >> $GITHUB_ENV
          else
            echo "no_op=false" >> $GITHUB_ENV
          fi

      - name: Set up DDN CLI and Login
        if: env.no_op != 'true'
        uses: hasura/ddn-deployment@main
        with:
          hasura-pat: ${{ secrets.HASURA_PAT }}

      - name: Install dependencies
        if: env.no_op != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create .env.cloud.test
        working-directory: ./hasura
        if: env.no_op != 'true'
        run: |
          echo "${{ secrets.ENV_CLOUD_DEFAULT }}" > .env.cloud.test

      - name: Detect Connector Changes
        if: env.no_op != 'true'
        run: |
          # Pull the base branch
          git fetch origin ${{ github.base_ref }}

          # Check if any changes occurred in the connector directories
          if git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep -q 'connector/'; then
            echo "connector_changes=true" >> $GITHUB_ENV
          else
            echo "connector_changes=false" >> $GITHUB_ENV
          fi

      - name: Install deploy script dependencies
        if: env.no_op != 'true'
        run: |
          cd ./scripts/deploy
          npm i

      - name: Build supergraph
        if: env.no_op != 'true'
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          if [ "${{ env.connector_changes }}" = "true" ]; then
            echo "Building connectors..."
            ./scripts/deploy/deploy.mjs \
              --context axiom-test \
              --profile telco \
              --override-description "${calculatedSha} [PR-${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}] Test build for commit $GITHUB_SHA" \
              --rebuild-connectors \
              --override \
              --log-level FATAL \
              --quiet \
              --no-interaction > build_output.json
          else
            echo "Skipping connector build."
            ./scripts/deploy/deploy.mjs \
              --context axiom-test \
              --profile telco \
              --override-description "${calculatedSha} [PR-${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}] Test build for commit $GITHUB_SHA" \
              --override \
              --log-level FATAL \
              --quiet \
              --no-interaction > build_output.json
          fi

      - name: Extract URLs from JSON
        if: env.no_op != 'true'
        run: |
          cat build_output.json
          BUILD_URLS=$(jq -r '.build_url' build_output.json | tr '\n' ',')
          CONSOLE_URLS=$(jq -r '.console_url' build_output.json | tr '\n' ',')
          echo "build_urls=${BUILD_URLS%,}" >> $GITHUB_ENV
          echo "console_urls=${CONSOLE_URLS%,}" >> $GITHUB_ENV

      - name: Add PR comment with build details
        if: env.no_op != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const buildUrls = process.env.build_urls.split(',').map(url => url.trim());
            const consoleUrls = process.env.console_urls.split(',').map(url => url.trim());
            const prNumber = context.payload.pull_request.number;
            const commitId = context.sha;

            const buildUrlsList = buildUrls.map(url => `- [${url}](${url})`).join('\n');
            const consoleUrlsList = consoleUrls.map(url => `- [${url}](${url})`).join('\n');

            const commentBody = `
            Supergraph build was successful! 🎉

            **Build URLs:**
            ${buildUrlsList}

            **Console URLs:**
            ${consoleUrlsList}

            **Commit ID:** ${commitId}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })

      - name: Add PR comment with no-op
        if: env.no_op != 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const commitId = context.sha;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**[no-op] build detected:** No build attempted\n**Commit ID:** ${commitId}`
            })

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for [no-op] in commit message
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^\[no-op\] ]]; then
            echo "no_op=true" >> $GITHUB_ENV
          else
            echo "no_op=false" >> $GITHUB_ENV
          fi

      - name: Set up DDN CLI and Login
        if: env.no_op != 'true'
        uses: hasura/ddn-deployment@main
        with:
          hasura-pat: ${{ secrets.HASURA_PAT }}

      - name: Install Dependencies (jq)
        if: env.no_op != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prep Repository
        if: env.no_op != 'true'
        run: |
          cp ./hasura/.env.template ./hasura/.env
          cp ./hasura/.env.local.template ./hasura/.env.local
          cp .data/.env.template .data/telco/.env

      - name: Build All Supergraphs
        working-directory: ./hasura
        if: env.no_op != 'true'
        run: |
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-config/telco/1-supergraph-project-queries.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-config/telco/2-supergraph-domain.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-config/telco/3-supergraph.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-config/telco/4-supergraph-with-mutations.yaml

      # TODO: could delete this too if everything is bundled into demo-telco
      - name: Set up demo databases
        working-directory: ./hasura
        if: env.no_op != 'true'
        run: ddn run docker-start-telco
        # TODO: delete this
        # run: DATASET=telco docker compose -f .data/compose.yaml --env-file .data/.env up --build --pull always -d

      - name: Set up demo databases & Run DDN
        working-directory: ./hasura
        if: env.no_op != 'true'
        env:
          HASURA_DDN_PAT: ${{ secrets.HASURA_PAT }}
        run: |
          ddn run demo-telco

        # TODO: delete this
        # docker compose -f compose.yaml \
        #  --env-file .env.local \
        #  --env-file .env \
        #  up --build --pull always -d

      - name: Wait for GraphQL Service to Be Ready
        if: env.no_op != 'true'
        run: |
          echo "Waiting for GraphQL service to start..."
          until curl -s http://localhost:3000/graphql -o /dev/null; do
            echo "Service not ready, retrying in 5 seconds..."
            sleep 5
          done
          echo "Service is up!"

      - name: Query DDN Endpoint and Validate Response
        if: env.no_op != 'true'
        run: |
          QUERY='{
            "query": "query getUsers { usersById(id: 1) { email formatCreatedAtTimestamp } customers(limit: 1) { firstName lastName email segment customerLinks { customerPreferences { socialMedia { linkedin } } supportDB { supportHistory { date status } } } creditCards { maskCreditCard expiry cvv } billings { formatBillingDate paymentStatus totalAmount } } calls(limit: 1) { callid } cdr(limit: 1) { guid } documents(limit: 1) { uuid } }"
          }'

          EXPECTED_RESPONSE='{
            "data": {
              "usersById": { "email": "adam.mcdaniel@bigpond.com", "formatCreatedAtTimestamp": "Sun Aug 18 2024" },
              "customers": [{
                "firstName": "Adam",
                "lastName": "Mcdaniel",
                "email": "adam.mcdaniel@bigpond.com",
                "segment": "family",
                "customerLinks": [{
                  "customerPreferences": { "socialMedia": { "linkedin": null } },
                  "supportDB": { "supportHistory": [{ "date": "2020-03-22", "status": "Resolved" }] }
                }],
                "creditCards": [{ "maskCreditCard": "***********8922", "expiry": "2028-04-23", "cvv": 651 }],
                "billings": [{ "formatBillingDate": "Thu Feb 02 2023", "paymentStatus": "overdue", "totalAmount": "50.50" }]
              }],
              "calls": [{ "callid": 188359 }],
              "cdr": [{ "guid": "dd264970-f61f-429f-97f8-4761fea4de2f" }],
              "documents": [{ "uuid": "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d" }]
            }
          }'

          RESPONSE=$(curl -s -X POST http://localhost:3000/graphql \
            -H "Content-Type: application/json" \
            -d "$QUERY")

          # Compare the actual response with the expected response
          if echo "$RESPONSE" | jq --argjson expected "$EXPECTED_RESPONSE" 'if . == $expected then "MATCH" else "MISMATCH" end' | grep -q "MATCH"; then
            echo "✅ Response matches expected output."
          else
            echo "❌ Response does not match expected output."
            echo "Expected: $EXPECTED_RESPONSE"
            echo "Got: $RESPONSE"
            exit 1
          fi
