on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up DDN CLI and Login
        uses: hasura/ddn-deployment@2.1.0
        with:
          hasura-pat: ${{ secrets.HASURA_PAT }}

      - name: Install Dependencies (jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prep Repository
        run: |
          cp .hasura/context.yaml.template .hasura/context.yaml
          cp .env.template .env
          cp .env.local.template .env.local

      - name: Build All Supergraphs
        run: |
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-project-queries.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-domain.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph.yaml
          ddn supergraph build local --env-file .env.local --env-file .env --supergraph supergraph-with-mutations.yaml

      - name: Set up demo databases
        run: DATASET=telco docker compose -f .data/compose.yaml --env-file .data/.env up --build --pull always -d

      - name: Run DDN
        env:
          HASURA_DDN_PAT: ${{ secrets.HASURA_PAT }}
        run: |
          docker compose -f compose.yaml \
            --env-file .env.local \
            --env-file .env \
            up --build --pull always -d
