name: Create Monday.com Item on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_monday_item:
    runs-on: ubuntu-latest

    env:
      title: ${{ github.event.issue.title }}
      body: ${{ github.event.issue.body }}

    steps:
    - name: Call Monday.com API
      run: |

        curl -X POST https://api.monday.com/v2 \
        -H "Authorization: ${{ secrets.MONDAY_API_KEY }}" \
        -H "Content-Type: application/json" \
        -d '{"query": "mutation { create_item(board_id: 6863162607, group_id: \"group_title\", item_name: \"'$title'\", column_values: \"{\\\"status\\\": {\\\"label\\\": \\\"New\\\"}, \\\"text\\\": \\\"$body\\\"}\") { id name } }"}'