services:
  customer_mongo:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-mongodb:v1.3.0
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $CUSTOMER_MONGO_HASURA_SERVICE_TOKEN_SECRET
      MONGODB_DATABASE_URI: $CUSTOMER_MONGO_MONGODB_DATABASE_URI
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $CUSTOMER_MONGO_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $CUSTOMER_MONGO_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "4038"
        protocol: tcp
